### ISSUE TITLE
Tracebacks and thread exceptions

### ISSUE THREAD

**Issue by itchybumkin** [therippa/pyAcurite#1]
First up, thanks for writing this. I feel a bit stiffed by Acurite - doubtless along with a horde of others - for having picked a weather hub for Acurite's kit that depends on a pointless service they provide in order to publish to WU, one which they have promised to pull next month coercing us into buying even more kit from them. 

To get to it, I installed this in an Ubuntu 18 shell in Windows Subsystem for Linux, updated the smarthub DHCP to use my own DNS, and routed the traffic to the WSL system. I needed to rollback a few binaries in order to be able to install the lot on the rqts list but believe I got there in the end. Flask runs the 'main' app in a debug mode and reports every time the 5-in-one reports via the Acurite smarthub. I would have loved to see how to autostart flask in WSL under Ubuntu to cover a Win10 blue screen/reboot situation, but more urgent than that are exceptions and tracebacks that I'm seeing for every instance of reported weather data. 

Here is an example. The IP 52.22.110.201 whose web service is spitting up a connection error is not mine, it apparently belongs to Amazon Web Svcs. 

Would you be able to shine some light on this?

[2019-01-08 23:29:38] Sending data: {"tempf": ["36.2"], "battery": ["normal"], "rainin": ["0.00"], "winddir": ["225"], "dewptf": ["36"], "PASSWORD": "*****", "ID": "IFRASERC2", "dateutc": ["now"], "realtime": ["1"], "windspeedmph": ["0"], "baromin": ["29.89"], "rtfreq": 30, "humidity": ["98"], "mt": ["5N1x31"], "dailyrainin": ["0.00"], "action": ["updateraw"], "rssi": ["1"], "sensor": ["00001440"]}
Exception in thread Thread-56:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/home/dirk/acurite/main.py", line 42, in send_it
    acurite = requests.get(url=('http://%s/weatherstation/updateweatherstation' % config.ACURITE_HUB_IP), params=raw_station_data)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='**52.22.110.201**', port=80): Max retries exceeded with url: /weatherstation/updateweatherstation?dateutc=now&mt=5N1x31&tempf=36.2&realtime=1&battery=normal&baromin=29.89&rainin=0.00&humidity=98&winddir=225&windspeedmph=0&action=updateraw&dewptf=36&rssi=1&dailyrainin=0.00&sensor=00001440&id=24C86E068323 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf407be510>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable',))

**Comment by therippa** [comment]
In your config file, change the hub api ip to 54.236.116.237 and see if that helps.  If not, at this point I would recommend checking out Acuparse, since it does what my little script does and **so** much more.

**Comment by itchybumkin** [comment]
Will try both. Thanks for the quick response.
